language: python
python:
  - "2.7"

install:
  - pwd
  - ls -l
  - source ./prepare.sh
  - conda info -a

cache:
  directories:
    - $TRAVIS_BUILD_DIR/pkginfo-cache

script:
  - echo Dummy
  - export
  - conda lsst build build:b1506 wcslib
