language: python
python:
  - "2.7"

install:
  - pwd
  - ls -l
  - source ./prepare.sh
  - conda info -a
  - export

cache:
  directories:
    - $TRAVIS_BUILD_DIR/pkginfo-cache

script:
  - conda lsst build build:b1507 lsst_distrib lsst_sims
